version: "3.8"

services:
  postgresql:
    image: postgres:latest
    container_name: medication-app-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/.pg-data/testTask:/var/lib/postgresql/data
